baseURL = "https://blog.nismit.me"
languageCode = "ja"
title = "NISLOG"
author = "NISMIT"
copyright = "Copyright (c) 2017 - NIGLOG all rights reserved."
canonifyurls = true
paginate = 5
pygmentsUseClasses = true
hasCJKLanguage = true
enableGitInfo = true
enableEmoji = true
theme = "humble"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = true

[taxonomies]
  tag = "tags"

[params]
  # dateformat = "Jan 2, 2006"
  dateformat = "2006/01/02"
  # Sets meta tag for keywords
  keywords = "canada, vancouver, 海外, バンクーバー, webdeveloper, フロントエンド, バックエンド, サーバー, wordpress, web開発, javascript"
  # Sets meta tag for description
  description = "フロントエンドやバックエンドに関する情報や勉強した事をアウトプットしています。カナダのバンクーバー在住ならではの情報なども少し書いています。"
  images = ["images/og_image.jpg"]

[outputs]
  home = ["HTML", "RSS"]
  posts = ["HTML", "RSS"]
  page = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[related]
  threshold = 80
  includeNewer = true
  toLower = false
[[related.indices]]
  name  = "tags"
  weight = 100
[[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2006"

[markup.goldmark.renderer]
  unsafe = true