baseURL = "https://blog.nismit.me/"
languageCode = "ja"
title = "NISLOG"
author = "NISMIT"
copyright = "Copyright (c) 2017 - NIGLOG all rights reserved."
canonifyurls = true
paginate = 5
pygmentsUseClasses = true
hasCJKLanguage = true
enableEmoji = true

[taxonomies]
  tag = "tags"

[params]
  # dateformat = "Jan 2, 2006"
  dateformat = "2006/01/02"
  # Sets meta tag for keywords
  keywords = "canada, vancouver, 海外, バンクーバー, webdeveloper, フロントエンド, バックエンド, サーバー, wordpress, web開発, javascript"
  # Sets meta tag for description
  description = "フロントエンドやバックエンドに関する情報や勉強した事をアウトプットしています。カナダのバンクーバー在住ならではの情報なども少し書いています。"

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"
