version: 2.1
jobs:
  build:
    docker:
      - image: nismit/hugo-firebase
    steps:
      - checkout
      - run:
          name: Init Submodule & Update
          command: git submodule sync && git submodule update --init
      - run:
          name: Build Hugo
          command: hugo -t humble --ignoreCache
      - deploy:
          name: Deploy to Firebase Hosting
          branch: master
          command: firebase deploy --token $FIREBASE_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
