name: Weekly Build
on:
  schedule:
    # Run every Saturday at 00:00
    - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check and Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL=$(gh pr list --base master --head develop --json "url,title" --jq '.[] | select(.title == "Weekly Build") | .url')
          if [ -z "$PR_URL" ]; then
            gh pr create \
              --base master \
              --head develop \
              --title "Weekly Build" \
              --body "This is an automated pull request for weekly build."
            # 作成されたPRのURLを取得
            PR_URL=$(gh pr list --base master --head develop --json "url,title" --jq '.[] | select(.title == "Weekly Build") | .url')
            echo "Created new PR: $PR_URL"
          else
            echo "PR already exists: $PR_URL"
          fi
          echo "pr_target_url=$PR_URL" >> $GITHUB_ENV
  auto_merge:
    needs: create_pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Auto-merging PR: $pr_target_url"
          gh pr merge "$pr_target_url" --rebase --auto || echo "Failed to auto-merge the PR"
